"""Latency benchmark harness for the FLAIME demo serving path (26Q1-DEMO-07).

Measures p50/p95 end-to-end transcription latency for clips of several
durations, on CPU and (if available) GPU, and renders a Markdown report.

Latency is the partner-facing metric — "what the partner will *feel*" — so the
target is concrete: <5 s wall-clock for a 10 s clip on the demo laptop (CPU).
``run_benchmark()`` is import-safe and engine-agnostic (it only calls
``engine.warmup()`` and ``engine.transcribe()``), so tests can drive it with a
stub engine without loading a real checkpoint.

Usage::

    uv run python -m scripts.bench_latency \\
        --checkpoint facebook/wav2vec2-base-960h --model-type wav2vec2 \\
        --out docs/research/DEMO07_latency.md
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any, Protocol

import numpy as np

# Duplicated from flaime_serving.inference.TARGET_SR on purpose: importing it
# would pull torch into this module's import path, but run_benchmark() is meant
# to be importable (and testable with a stub) without the heavy serving deps —
# torch is only imported lazily in _build_engine().
TARGET_SR = 16_000  # Hz
DEFAULT_DURATIONS_S: tuple[int, ...] = (1, 5, 10, 30)
DEFAULT_REPEATS = 10
LATENCY_TARGET_S = 5.0  # <5 s for a 10 s clip on the target CPU laptop
TARGET_CLIP_S = 10
# The curated, hand-maintained report (two model sections, hardware caveats,
# fallback prose) lives at docs/research/DEMO07_latency.md. This harness emits a
# bare single-table report to a *separate* generated file to fold in by hand —
# never default --out to the curated doc or it gets clobbered. Anchor both to
# the repo root (this file is scripts/bench_latency.py) so the clobber guard
# is correct regardless of the caller's working directory.
_REPO_ROOT = Path(__file__).resolve().parents[1]
CURATED_REPORT = _REPO_ROOT / "docs/research/DEMO07_latency.md"
DEFAULT_OUT = _REPO_ROOT / "docs/research/DEMO07_latency.generated.md"


class _Transcriber(Protocol):
    """Structural type for anything ``run_benchmark`` can drive."""

    device: str

    def warmup(self) -> None: ...

    def transcribe(
        self, audio: Any, language: str | None = ..., *, sample_rate: int | None = ...
    ) -> Any: ...


def run_benchmark(
    engine: _Transcriber,
    durations_s: tuple[int, ...] = DEFAULT_DURATIONS_S,
    repeats: int = DEFAULT_REPEATS,
) -> list[dict[str, Any]]:
    """Measure p50/p95 transcription latency per clip duration.

    Synthetic silence is generated in RAM — no disk or network I/O — so this is
    safe to run anywhere, including CI with a stub engine.  Each duration's
    *shape* is warmed with one throwaway transcription immediately before its
    timed loop — so shape-keyed cold-start (e.g. GPU cuDNN autotune that re-fires
    per input length) does not inflate the first timed sample's p95.  The first
    such per-shape warm also pays the one-time global cold-start, so no separate
    up-front ``warmup()`` call is needed here.

    Args:
        engine: Object exposing ``warmup()`` and ``transcribe(audio,
            sample_rate=...)``; in production an ``ASRInferenceEngine``.
        durations_s: Clip lengths to measure, in seconds.
        repeats: Number of timed transcriptions per duration (must be >= 1).

    Returns:
        One row per duration, each a dict with keys ``duration_s``, ``device``,
        ``p50_ms``, ``p95_ms``, ``n`` (and ``mean_ms``).  Sorted by duration.

    Raises:
        ValueError: If ``repeats`` is less than 1 (an empty sample set has no
            meaningful percentile).
    """
    if repeats < 1:
        raise ValueError(f"repeats must be >= 1, got {repeats}.")
    device = getattr(engine, "device", "unknown")
    rows: list[dict[str, Any]] = []
    for dur in sorted(durations_s):
        audio = np.zeros(int(dur * TARGET_SR), dtype=np.float32)
        engine.transcribe(audio, sample_rate=TARGET_SR)  # warm this shape
        samples = [
            engine.transcribe(audio, sample_rate=TARGET_SR).latency_ms
            for _ in range(repeats)
        ]
        rows.append(
            {
                "duration_s": dur,
                "device": device,
                "p50_ms": float(np.percentile(samples, 50)),
                "p95_ms": float(np.percentile(samples, 95)),
                "mean_ms": float(np.mean(samples)),
                "n": repeats,
            }
        )
    return rows


def render_markdown(rows: list[dict[str, Any]], *, checkpoint: str) -> str:
    """Render benchmark *rows* as the DEMO07_latency.md report body."""
    lines = [
        "# DEMO-07 Latency Benchmark (auto-generated)",
        "",
        "> Generated by `scripts/bench_latency.py`. Fold these numbers into "
        "the curated `docs/research/DEMO07_latency.md` by hand — that file has "
        "prose this harness cannot reproduce.",
        "",
        f"Checkpoint: `{checkpoint}`",
        "",
        f"Target: **<{LATENCY_TARGET_S:.0f} s** wall-clock for a "
        f"{TARGET_CLIP_S} s clip on the demo laptop (CPU).",
        "",
        "| Duration (s) | Device | p50 (ms) | p95 (ms) | mean (ms) | n |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['duration_s']} | {r['device']} | {r['p50_ms']:.1f} | "
            f"{r['p95_ms']:.1f} | {r['mean_ms']:.1f} | {r['n']} |"
        )
    lines.append("")
    target_rows = [r for r in rows if r["duration_s"] == TARGET_CLIP_S]
    if not target_rows:
        lines.append(
            f"**{TARGET_CLIP_S} s target**: not benchmarked — re-run with "
            f"`--durations … {TARGET_CLIP_S} …` to record the acceptance verdict."
        )
    for r in target_rows:
        met = r["p95_ms"] <= LATENCY_TARGET_S * 1000
        verdict = "✅ met" if met else "❌ MISSED — document fallback"
        lines.append(
            f"**{TARGET_CLIP_S} s target ({r['device']})**: "
            f"p95 {r['p95_ms']:.0f} ms — {verdict}."
        )
    lines.append("")
    return "\n".join(lines)


def _build_engine(checkpoint: str, model_type: str, device: str | None) -> _Transcriber:
    """Construct a real ASRInferenceEngine (imported lazily for test isolation)."""
    from flaime_serving import ASRInferenceEngine

    return ASRInferenceEngine.load(
        checkpoint, model_type=model_type, device=device, warmup=False
    )


def main(argv: list[str] | None = None) -> int:
    """CLI entry point: benchmark a checkpoint and write the Markdown report."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--checkpoint", required=True, help="Checkpoint path or HF ID.")
    parser.add_argument("--model-type", required=True, help="ASRModelFactory key.")
    parser.add_argument(
        "--device", default=None, help="Torch device (default: auto-detect)."
    )
    parser.add_argument(
        "--durations",
        type=int,
        nargs="+",
        default=list(DEFAULT_DURATIONS_S),
        help="Clip durations in seconds.",
    )
    parser.add_argument("--repeats", type=int, default=DEFAULT_REPEATS)
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help=f"Markdown report output path (default: {DEFAULT_OUT}).",
    )
    args = parser.parse_args(argv)

    if args.out.resolve() == CURATED_REPORT.resolve():
        parser.error(
            f"refusing to overwrite the curated report {CURATED_REPORT}; "
            f"write to a generated file (default {DEFAULT_OUT}) and fold in by hand."
        )

    engine = _build_engine(args.checkpoint, args.model_type, args.device)
    rows = run_benchmark(engine, tuple(args.durations), args.repeats)
    report = render_markdown(rows, checkpoint=args.checkpoint)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(report)
    print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
